version: '2.2'

services:
  dse:
    container_name: dse
    image: datastax/dse-server:6.8.0
    command: -s -k
    environment:
        - "DS_LICENSE=accept"
    volumes:
        - ./config:/config
  studio:
    container_name: studio
    image: "datastax/dse-studio"
    environment:
      - DS_LICENSE=accept
    ports:
      - 9091:9091
  dsbulk-deployer:
    build: ./../dsbulk-deployer-app
